### ISSUE TITLE
Change background to every 20 points won.

### ISSUE THREAD

**Issue by rodrigets** [rodrigets/games-in-pygame#10]
Change background to every 20 points won.
obs: It depends on the issue https://github.com/rodrigets/games-in-pygame/issues/9

**Comment by murilexbarbosa** [comment]
I'll do this for you

**Comment by AK-007** [comment]
Can you tell me how to install dependencies?
Where should i keep the project folder?

**Comment by AK-007** [comment]
No need.
I'll try to implement the background change.

**Comment by rodrigets** [comment]
Hi @AK-007 ,
I think it's interesting to give a master pull because there was a change in the background recently.
If you still have questions, please let me know.
Thank you.

**Comment by Nitish18** [comment]
Hi @rodrigets ,
please check PR #19 for this issue. You feedback will be appreciated.

**Comment by rodrigets** [comment]
Very good @Nitish18 
In the future add more backgorunds and make it be changed with a slightly higher score, giving the feeling of passing level.
Thank you

**Comment by rodrigets** [comment]
https://github.com/rodrigets/games-in-pygame/pull/19
