### ISSUE TITLE
Make the background of the screen move, giving a sense of navigation

### ISSUE THREAD

**Issue by rodrigets** [rodrigets/games-in-pygame#2]

**Comment by Zorrette** [comment]
Hey !
I think what you want to do is not very explicit :
- Do you want to lock the ship on the middle of the window and just have the background moving to make the impression of navigation ?
- Do you want to define max size for the map and while on it move the map and the ship until the edges ?
- Do you want to be able to actually move the ship if you are in the center of the map and when going forward only the map moves ?
- Do you want an infinite map or not ?

(I hope it's clear...)
I might get to it, but I need an answer before =)

**Comment by rodrigets** [comment]
Hi @Zorrette,
- I just wish the background moves down, giving the feeling that the ship is accelerating in space.
"The ship continues with the same mechanics.
- The map is infinite yes, because in the future when the user reaches a certain score I will change the background and the image of the asteroids, giving the sensation of changing the phase.

I hope I have healed my doubts.
Thank you.

**Comment by nagoli104** [comment]
Hi @Zorrette,
are you working on this? I might have a solution to this issue, if you don't mind.

**Comment by rodrigets** [comment]
https://github.com/rodrigets/games-in-pygame/pull/12
