### ISSUE TITLE
 Improve asteroid speed and change background by 40 points.

### ISSUE THREAD

**Issue by rodrigets** [rodrigets/games-in-pygame#22]

**Comment by V1shvesh** [comment]
Can I have a go?

**Comment by rodrigets** [comment]
@V1shvesh , yes yes

**Comment by V1shvesh** [comment]
Can you explain the issue more please?

**Comment by rodrigets** [comment]
Thank you @V1shvesh 
But I have already made this change, I will upload it soon.

**Comment by rodrigets** [comment]
https://github.com/rodrigets/games-in-pygame/pull/26
