### ISSUE TITLE
Add thematic music to the game

### ISSUE THREAD

**Issue by rodrigets** [rodrigets/games-in-pygame#29]

**Comment by priyalaggarwal** [comment]
By thematic music you mean background music?

**Comment by rodrigets** [comment]
Hi @priyalaggarwal .

Yes, Background music, matching the spaceship game

**Comment by priyalaggarwal** [comment]
I wanted to work on this.

**Comment by rodrigets** [comment]
Hi @priyalaggarwal 
Ok.

**Comment by rodrigets** [comment]
Hi, @Codarus !
Please move the mp3 file into the resource folder.
Thank you.

**Comment by Codarus** [comment]
Hi, @rodrigets,

The mp3 file has been moved to the resource folder.
Thank you.

**Comment by rodrigets** [comment]
Thank you @Codarus
