### ISSUE TITLE
Spaceship is able to shoot even when the game is over

### ISSUE THREAD

**Issue by priyalaggarwal** [rodrigets/games-in-pygame#30]
When the game gets over due to collision, even then, if you press spacebar before closing or restarting the game, you can shoot. Is that intentional?

**Comment by nagoli104** [comment]
No, I missed this when implementing the shooting function. I will look into it.

**Comment by rodrigets** [comment]
Tks @nagoli104 !
close https://github.com/rodrigets/games-in-pygame/pull/31
