### ISSUE TITLE
Make the game two player, adding another ship to be controlled by the keys [W] - [S] - [D] - [X - shot]

### ISSUE THREAD

**Issue by rodrigets** [rodrigets/games-in-pygame#42]

**Comment by sandybisaria** [comment]
Hello, I'd like to help with this

**Comment by sandybisaria** [comment]
Should it be two-player only or should there be an option to switch between one-player and two-player?

**Comment by rodrigets** [comment]
@sandybisaria 
Yes, sorry not to report.
You should have the option of one or two players.

**Comment by rodrigets** [comment]
@sandybisaria !
Very good!
Thanks.
