### ISSUE TITLE
Generate apk for android file.

### ISSUE THREAD

**Issue by rodrigets** [rodrigets/games-in-pygame#45]

**Comment by korsakjakub** [comment]
Can you elaborate on what you meant by that? Do you want the game to be put in an android app?

**Comment by rodrigets** [comment]
@korsakjakub ,
That's it.
Tips: https://trypix.wordpress.com/2015/05/11/android-python-e-pygame/

**Comment by korsakjakub** [comment]
Ok I'll look into that
