### ISSUE TITLE
Generate executable

### ISSUE THREAD

**Issue by rodrigets** [rodrigets/games-in-pygame#54]
Generate executable  for Windows(.exe) and Linux(.deb).

**Comment by marce1994** [comment]
i will give it a try, can i use py2exe or PyInstaller?
You need an exe, or the script to generate the executables?
Thanks!

**Comment by rodrigets** [comment]
Hi @marce1994 !
You can use either of the two options.
It would be cool the script and also the exe.
Enter a new folder in the project with the exe and the script for generation.

**Comment by salvadorrueda** [comment]
Hi @rodrigets I'll try the .deb 

I'm reading this [http://www.king-foo.com/2011/11/creating-debianubuntu-deb-packages/](http://www.king-foo.com/2011/11/creating-debianubuntu-deb-packages/)
I think it'll be useful.

**Comment by marce1994** [comment]
Sorry about the time, i were at work :'v.
I think it is ok. maybe changing the folder name... or putting in DEBIAN too in the same one

**Comment by salvadorrueda** [comment]
Don't worry. I was sleeping :sleeping:, like almost everyone in spain :es: at that time

Maybe the best solution is create a new structure 
      DISTRIBUTION
with two subfolders, one for each distribution type.
      DEBIAN  
      WINDOWS

**Comment by rodrigets** [comment]
Hi @salvadorrueda !
Thanks for the contribution and I'm glad to hear that you learned a bit more about debian.

Happy Hacktoberfest!

**Comment by rodrigets** [comment]
@marce1994 , 
I'm at work and only have linux machine.
As soon as I get home I check your PR okay?
But I already leave you my thanks.

**Comment by marce1994** [comment]
@rodrigets yes, no problem :).
you can use a Virtual machine if you want, personally i prefer to program into a virtual machine 👍

**Comment by rodrigets** [comment]
Congratulations guys!
Actually, your work was very good.
If you want to close more partnerships in game development, let me know.
I do some games with godot engine too.

**Comment by salvadorrueda** [comment]
Thanks :D

It's good to know you also develop with godot.
I never used it before but I'm always willing to learn although right now
I'm really interested in AI.

**Comment by marce1994** [comment]
i usually work with c# .Net core and Unity3D.
I'm interested in AI, and videogames too :). (I'm looking at Acid Game Engine).

It is good to know that my work is good.

while i was trying the project into my virtual machine, i noticed that without sound card, the project does not work, that's correct? Literally, my virtual machine's sound card was broken

Thanks for the feedback 👍 !

**Comment by rodrigets** [comment]
Nice, @salvadorrueda  !
IA is very cool too, in the future I will study a little too.
If you are interested, take a look:
https://godotengine.org/
is very similar to python.
See you.

**Comment by rodrigets** [comment]
Hi @marce1994 !
I'm also starting to see Unity3D.
I did not get to test this case.
I'll take a look to see what can happen.
Thank you.
