### ISSUE TITLE
Add counter based on the destroyed asteroids

### ISSUE THREAD

**Issue by rodrigets** [rodrigets/games-in-pygame#9]
Add counter based on the destroyed asteroids and display at the top right of the screen as a way to score.
For each shot that collides with the asteroid, add 5 to the counter.

**Comment by murilexbarbosa** [comment]
I'll do this for you

**Comment by AK-007** [comment]
PR #13 implemented.
plz review :)

**Comment by rodrigets** [comment]
tks @AK-007 
https://github.com/rodrigets/games-in-pygame/pull/13
